### PR TITLE
fix node_modules directory bug

### PR DESCRIPTION
**Pull request by shadowcodex**
Check to see if node_modules is in our path before we add it. If it is go ahead and remove it.

### CODE REVIEW

**Comment by shadowcodex** [comment]
Any response to this PR?

**Comment by evertton** [comment]
Sorry, I was busy with other activities. Even today, check this pull request.

**Comment by evertton** [comment]
I made a superficial analysis and judged correct this pull request, but just introducing a new problem. Check the 0.1.6 version available on npm.

**Comment by evertton** [comment]
I will work on more robust solution, think of something, please suggest.

**Comment by shadowcodex** [comment]
Well how about bringing mr-doc into he plugin locally. Instead of trying to go outside the plugin and back into a directory?

**Comment by evertton** [comment]
I fixed this issue, but the Mr. Doc has a problem.

**Comment by shadowcodex** [comment]
Ah ok.

**Pull request merged**
